services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: GestionClinique
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: D:\data\cours\Angular\pk48\clinique\back-end\GestionClinique\compose.yaml # CORRECTED PATH HERE!
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/GestionClinique
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  pgdata: