package com.example.GestionClinique.mapper;

import com.example.GestionClinique.dto.RequestDto.RendezVousRequestDto;
import com.example.GestionClinique.dto.ResponseDto.RendezVousResponseDto;
import com.example.GestionClinique.model.entity.Patient;
import com.example.GestionClinique.model.entity.RendezVous;
import com.example.GestionClinique.model.entity.Salle;
import com.example.GestionClinique.model.entity.Utilisateur;
import com.example.GestionClinique.repository.PatientRepository;
import com.example.GestionClinique.repository.SalleRepository;
import com.example.GestionClinique.repository.UtilisateurRepository;
import org.mapstruct.*;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

@Mapper(componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public abstract class RendezVousMapper {

    // In RendezVousMapper
    @Autowired // Inject repositories into the mapper
    private PatientRepository patientRepository;
    @Autowired
    private UtilisateurRepository utilisateurRepository;
    @Autowired
    private SalleRepository salleRepository;

    @Mapping(target = "id", ignore = true) // Assuming ID is generated by DB
    @Mapping(target = "patient", source = "patientId", qualifiedByName = "mapPatientIdToPatient")
    @Mapping(target = "medecin", source = "medecinId", qualifiedByName = "mapMedecinIdToMedecin")
    @Mapping(target = "salle", source = "salleId", qualifiedByName = "mapSalleIdToSalle")
    public abstract RendezVous toEntity(RendezVousRequestDto dto);

    @Named("mapPatientIdToPatient")
    public Patient mapPatientIdToPatient(Long patientId) {
        if (patientId == null) {
            return null;
        }
        return patientRepository.findById(patientId)
                .orElseThrow(() -> new IllegalArgumentException("Patient not found with ID: " + patientId));
    }

    @Named("mapMedecinIdToMedecin")
    public Utilisateur mapMedecinIdToMedecin(Long medecinId) {
        if (medecinId == null) {
            return null;
        }
        return utilisateurRepository.findById(medecinId)
                .orElseThrow(() -> new IllegalArgumentException("Medecin not found with ID: " + medecinId));
    }

    @Named("mapSalleIdToSalle")
    public Salle mapSalleIdToSalle(Long salleId) {
        if (salleId == null) {
            return null;
        }
        return salleRepository.findById(salleId)
                .orElseThrow(() -> new IllegalArgumentException("Salle not found with ID: " + salleId));
    }

    @Mapping(source = "patient.id", target = "patientId")
    @Mapping(source = "medecin.id", target = "medecinId")
    @Mapping(source = "salle.id", target = "salleId")
    @Mapping(target = "patientNomComplet", expression = "java(entity.getPatient() != null ? entity.getPatient().getNom() + \" \" + entity.getPatient().getPrenom() : null)")
    @Mapping(target = "medecinNomComplet", expression = "java(entity.getMedecin() != null ? entity.getMedecin().getNom() + \" \" + entity.getMedecin().getPrenom() : null)")
    @Mapping(source = "salle.numeroSalle", target = "nomSalle")
    public abstract RendezVousResponseDto toDto(RendezVous entity);

    public abstract List<RendezVousResponseDto> toDtoList(List<RendezVous> entities);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "patient", ignore = true)
    @Mapping(target = "medecin", ignore = true)
    @Mapping(target = "salle", ignore = true)
    @Mapping(target = "consultation", ignore = true)
    public abstract void updateEntityFromDto(RendezVousRequestDto dto, @MappingTarget RendezVous entity);
}
